### ISSUE TITLE
relevantEvents is always blank

### ISSUE THREAD

**Issue by nitinsurana** [alexa/skill-sample-nodejs-calendar-reader#15]
Hi,

I'm having a hard-time getting relevantEvents to work for eventIntent. I believe the relevantEvents is not getting saved and hence, every time the lambda function executes, it's blank.

**Comment by nitinsurana** [comment]
Got it why relevantEvents sometimes work and sometimes doesn't.

```
 Requiring functions to be stateless enables AWS Lambda to launch as many copies of a function as
 needed to scale to the incoming rate of events and requests. These functions may not always run 
on the same compute instance from request to request, and **a given instance of your Lambda 
function may be used more than once by AWS Lambd**a.

Q: Will AWS Lambda reuse function instances?
To improve performance, AWS Lambda may choose to retain an instance of your function and reuse 
it to serve a subsequent request, rather than creating a new copy. Your code should not assume 
that this will always happen.
```



http://rodos.haywood.org/2015/06/lambda-functions-idempotent.html

**Comment by nitinsurana** [comment]
For everyone else, the fix can be found here - https://github.com/nitinsurana/dorm-events-alexa/blob/master/src/index.js#L326

**Comment by dskrad** [comment]
I have not tried this example yet. I was reviewing the code and I was wondering how the variable relevantEvents persisted between the search state and the description state. It seems the array is only populated during the search state, then if events are found the state changes to description state. 

The way I understand it, the variable must persist as long as the skill does not timeout. I am not sure how this is achieved given the fact that in the middle of a session, the lambda function call may not persist your variables.
