### ISSUE TITLE
Lambda function errors out

### ISSUE THREAD

**Issue by su7edja** [alexa/skill-sample-nodejs-calendar-reader#17]
I'm following the tutorial and I'm having trouble in the testing section. The lambda function errors out. Here's the log output:

```
START RequestId: 2fbcfe89-d08d-11e6-a91d-4fb848ee7914 Version: $LATEST
2017-01-02T01:45:50.007Z	2fbcfe89-d08d-11e6-a91d-4fb848ee7914	TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:102:38)
    at AlexaRequestEmitter.Object.defineProperty.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:91:31)
    at exports.handler (/var/task/index.js:267:11)
END RequestId: 2fbcfe89-d08d-11e6-a91d-4fb848ee7914
REPORT RequestId: 2fbcfe89-d08d-11e6-a91d-4fb848ee7914	Duration: 120.75 ms	Billed Duration: 200 ms 	Memory Size: 128 MB	Max Memory Used: 35 MB	
RequestId: 2fbcfe89-d08d-11e6-a91d-4fb848ee7914 Process exited before completing request
```

Node version: v6.5.0
npm version: 3.10.3

edited:
even after adding the changes proposed in #9 and #11 , I'm still getting the same error.

**Comment by su7edja** [comment]
Closing this. It was because installation of alexa-sdk wasnt in the right place

**Comment by thomseninteractive** [comment]
I am having the same problem.  Are you using the included ics reference or another one?  I get more consistent results with the Stanford ics, though it still occasionally yields a remote endpoint error.  For another ics I found that changing the url from https to http also seemed to give me more success, but it is still not consistent.  'Wondering if there is something to how large of an ics it can process.  I put one in S3 to reduce possibly latency but still get the remote endpoint errors.

**Comment by su7edja** [comment]
@thomseninteractive  yeah you are right. I tried it again and finally for the first time got it to work once. Then I get that same error again.

When I used a smaller ics file, it is more consistent.
