### ISSUE TITLE
Unable to read facebook webcal even after replacing webcal:// to https://

### ISSUE THREAD

**Issue by nitinsurana** [alexa/skill-sample-nodejs-calendar-reader#5]
Trying to use the "Upcoming Events" link in the bottom right corner of [facebook events page](https://www.facebook.com/events/upcoming) in ical throws "WebUnsupportedBrowser".

Tried by replacing webcal:// to https:// still didn't worked. If I paste the https:// url in browser, it successfully downloads the .ics file.

**Comment by nitinsurana** [comment]
Set "User-Agent" in the request for facebook ics.

My code looks like


```
    request({
        url: URL,
        headers: {
            'User-Agent': 'Mozilla/5.0 (Node.js 6.0.0) MagicMirror/2.0 (https://github.com/MichMich/MagicMirror)'
        }
    }, function (error, res, data) {
        data = ical.parseICS(data);
```

**Comment by talk2camden** [comment]
Wait-- How did you fix this? I can't figure it out.
