### ISSUE TITLE
ical.fromURL in ical not working

### ISSUE THREAD

**Issue by GShank12345** [alexa/skill-sample-nodejs-calendar-reader#50]
I am trying to fix an issue with ical.fromURL(URL, {}, function (error, data) . My problem is it is not taking the function. When I tried returning a value from the function it returns "Undefined". Did anyone encounter this problem? How to fix this?

**Comment by 0a01-wait** [comment]
did you ever solve this problem?  thanks.

**Comment by GShank12345** [comment]
No

**Comment by lovelle3025** [comment]
No and I got this from the Amazon Alexa templates in Github and it isnt
working right so it wont get certified.I dont know how to fix it so I would
not recommend this template to others.


*Maria McCoy, Founder*
Screen Lizyrds
screenlizyrds@gmail.com
https://screenlizards.wordpress.com/

**Comment by 0a01-wait** [comment]
thanks.  yes i got it from the same site.  my expertise is in assembler language, not javascript/json, so I'm having to use a machete to hack through these problems.  I've looked in the ical directory that gets dragged in and it doesn't even seem to make it into the code.
did you also have to edit outside the Lambda environment because of the 7mb size of all the code that gets dragged in (which is ridiculous)?

**Comment by lovelle3025** [comment]
Yes I used ATOM and I had to keep saving and zipping the files and
uploading through the Lambda upload. I only have about 15 questions.


*Maria McCoy, Founder*
Screen Lizyrds
screenlizyrds@gmail.com
https://screenlizards.wordpress.com/

**Comment by lovelle3025** [comment]
If you give me your email maybe i can add you to the testers and tell me
what you think the issue is.


*Maria McCoy, Founder*
Screen Lizyrds
screenlizyrds@gmail.com
https://screenlizards.wordpress.com/

**Comment by GShank12345** [comment]
Yes.. I could fix the above issue that I created in node.js by putting this.emit(':responseReady') just before 
}.bind(this)); . 
The code does work but I did few customizations from my end.

**Comment by 0a01-wait** [comment]
Ive tried all sorts of variations of that fix to no avail.  Which .js file did you modify, and where did you place the this.emit(':responseReady')? Thanks

**Comment by GShank12345** [comment]
In Index.js for the search Intent

     'searchIntent': function () {
        // Declare variables
         this.URL=URL;
        let eventList = new Array();
        let slotValue = this.event.request.intent.slots.date.value;
        console.log("URL heading" + URL);
        if (slotValue != undefined)
        {
            // Using the iCal library I pass the URL of where we want to get the data from.
            console.log("URL " + URL + slotValue);
            ical.fromURL(URL, {}, function (error, data) {
                // Loop through all iCal data found
                for (let k in data) {
                    if (data.hasOwnProperty(k)) {
                        let ev = data[k];
                   //     console.log("ev="+data[k]);
                        // Pick out the data relevant to us and create an object to hold it.
                       let eventData = {
                          summary: (ev.summary),
                            location: (ev.location),
                            description:(ev.description),
                            start: ev.start
                        };
                        // add the newly created object to an array for use later.
                        eventList.push(eventData);
                    }
                } // for let k
                // Check we have data
                console.log("event list =" + eventList.length);
                if (eventList.length > 0) {
                    // Read slot data and parse out a usable date
                    console.log("event data="+ slotValue + eventList.length);
                    let eventDate = getDateFromSlot(slotValue);
                    // Check we have both a start and end date
                    console.log("Date " + eventDate.startDate + " " + eventDate.endDate);
                    if (eventDate.startDate && eventDate.endDate) {
                        // initiate a new array, and this time fill it with events that fit between the two dates
                        relevantEvents = getEventsBeweenDates(eventDate.startDate, eventDate.endDate, eventList);
                       console.log("relevant events="+ relevantEvents.length);
                       if (relevantEvents.length > 0) {
                            // change state to description
                        //    this.handler.state = states.DESCRIPTION;

                            // Create output for both Alexa and the content card
                            console.log("relevant events="+ relevantEvents.length);
                            let cardContent = "";
                            if (relevantEvents.length == 1) {
                               output = utils.format(multipleEventMessage, relevantEvents.length);
                                 output = oneEventMessage;
                           }
                          
                            // describes the number of events
                            if (relevantEvents.length > 1) {
                               output = utils.format(multipleEventMessage, relevantEvents.length);
                           }

                            output += scheduledEventMessage;

                            if (relevantEvents.length > 1) {
                                output += utils.format(firstThreeMessage, relevantEvents.length > 7 ? 7 : relevantEvents.length);
                            } 

                            if (relevantEvents[0] != null) {
                                let date = new Date(relevantEvents[0].start);
                                if (relevantEvents[0].location != null)
                                {
                                output += utils.format(eventSummary, "First", relevantEvents[0].summary, relevantEvents[0].location, date.toDateString() + ".");
                                }
                                else
                                {
                                    output += utils.format(eventSummary, "First", relevantEvents[0].summary, 'location unknown',date.toDateString() + ".");
                                
                                }
                                }
                                    
                               
                            if (relevantEvents[1] != null) {
                               let date = new Date(relevantEvents[1].start);
                              if (relevantEvents[1].location != null)
                                {
                                output += utils.format(eventSummary, "Second", relevantEvents[1].summary, relevantEvents[1].location, date.toDateString() + ".");
                                }
                                else
                                {
                                    output += utils.format(eventSummary, "Second", relevantEvents[1].summary, 'location unknown', date.toDateString() + ".");
                                
                                }
                                }
                                   
                            
                             if (relevantEvents[2] != null) {
                               let date = new Date(relevantEvents[2].start);
                                if (relevantEvents[2].location != null)
                                {
                                output += utils.format(eventSummary, "Third", relevantEvents[2].summary, relevantEvents[2].location, date.toDateString() + ".");
                                }
                                else
                                {
                                    output += utils.format(eventSummary, "Third", relevantEvents[2].summary, 'location unknown', date.toDateString() + ".");
                                
                                }
                                }
                                   
                            if (relevantEvents[3] != null) {
                               let date = new Date(relevantEvents[3].start);
                               if (relevantEvents[3].location != null)
                                {
                                output += utils.format(eventSummary, "Fourth", relevantEvents[3].summary, relevantEvents[3].location, date.toDateString() + ".");
                                }
                                else
                                {
                                    output += utils.format(eventSummary, "Fourth", relevantEvents[3].summary,  'location unknown', date.toDateString() + ".");
                                
                                }
                                }
                                   
                           if (relevantEvents[4] != null) {
                               let date = new Date(relevantEvents[4].start);
                                 if (relevantEvents[4].location != null)
                                {
                                output += utils.format(eventSummary, "Fifth", relevantEvents[4].summary, relevantEvents[4].location, date.toDateString() + ".");
                                }
                                else
                                {
                                    output += utils.format(eventSummary, "Fifth", relevantEvents[4].summary,  'location unknown', date.toDateString() + ".");
                                
                                }
                                }
                                   
                             if (relevantEvents[5] != null) {
                               let date = new Date(relevantEvents[5].start);
                                  if (relevantEvents[5].location != null)
                                {
                                output += utils.format(eventSummary, "Sixth", relevantEvents[5].summary, relevantEvents[5].location, date.toDateString() + ".");
                                }
                                else
                                {
                                    output += utils.format(eventSummary, "Sixth", relevantEvents[5].summary,  'location unknown', date.toDateString() + ".");
                                
                                }
                                }
                                   
                             if (relevantEvents[6] != null) {
                               let date = new Date(relevantEvents[6].start);
                                if (relevantEvents[6].location != null)
                                {
                                output += utils.format(eventSummary, "Seventh", relevantEvents[6].summary, relevantEvents[6].location, date.toDateString() + ".");
                                }
                                else
                                {
                                    output += utils.format(eventSummary, "Seventh", relevantEvents[6].summary,  'location unknown', date.toDateString() + ".");
                                
                                }
                                }
                                    

                            for (let i = 0; i < relevantEvents.length; i++) {
                                let date = new Date(relevantEvents[i].start);
                                if (relevantEvents[i].location != null) {
                                cardContent += utils.format(cardContentSummary, (relevantEvents[i].summary), (relevantEvents[i].location), date.toDateString());
                                }
                                else
                                {
                                   cardContent += utils.format(cardContentSummary, (relevantEvents[i].summary), date.toDateString());
                                
                                }
                            }
                       
                            output += eventNumberMoreInfoText;
                            this.response.cardRenderer(cardTitle, cardContent);
                            this.response.speak(output).listen('repeat');
                             
                        } // if (relevant event.lenghth > 0) 
                        else {
                            output = NoDataMessage;
                            this.response.speak(output).listen(output);
                        }
                    } // if event.startdate
                    else {
                        output = NoDataMessage;
                        this.response.speak(output).listen(output);
                    }
                } 
                else {
                    output = NoDataMessage;
                    this.response.speak(output).listen(output);
                }
                this.emit(':responseReady');
            }.bind(this));
      
        }
        else{
            this.response.speak("I'm sorry.  What date did you want me to look for events?").listen("I'm sorry.  What day did you want me to look for events?");
            this.emit(':responseReady');
        }
 },

**Comment by 0a01-wait** [comment]
that did the trick - thanks so much!
